import { MediaItem, ContinueWatchingItem } from '@/types/cinema';
import { WatchGroup } from '@/types/watchTogether';
import { ChatMessage } from '@/types/chat';
import { AdminTelemetrySummary } from '@/types/admin';
import { MediaSegment } from '@/types/segments';

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II, exploring the profound moral dilemmas and political consequences that followed.',
    type: 'movie',
    runtime: '3h 00m',
    releaseYear: 2023,
    rating: 'R',
    matchScore: 99,
    genres: ['Biography', 'Drama', 'History'],
    badges: ['4K UHD', 'Dolby Atmos', 'Dolby Vision', 'IMAX Enhanced'],
    posterUrl: 'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'],
    audioFormats: ['DTS-HD MA 5.1', 'French (5.1)'],
    subtitleLanguages: ['English [CC]', 'Spanish'],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    hasDolbyIntro: true,
  },
  {
    id: 'spider-man-across-the-spider-verse',
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'It’s how you wear the mask that matters.',
    overview: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence.',
    type: 'movie',
    runtime: '2h 20m',
    releaseYear: 2023,
    rating: 'PG',
    matchScore: 97,
    genres: ['Animation', 'Action', 'Adventure', 'Sci-Fi'],
    badges: ['4K UHD', 'Dolby Atmos', 'Dolby Vision'],
    posterUrl: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    director: 'Joaquim Dos Santos, Kemp Powers',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Jake Johnson', 'Daniel Kaluuya'],
    audioFormats: ['Dolby Atmos', 'Spanish 5.1'],
    subtitleLanguages: ['English [CC]', 'Spanish'],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    hasDolbyIntro: true,
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival as Earth faces catastrophic environmental collapse.',
    type: 'movie',
    runtime: '2h 49m',
    releaseYear: 2014,
    rating: 'PG-13',
    matchScore: 96,
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    badges: ['4K UHD', 'Dolby Atmos', 'IMAX Enhanced'],
    posterUrl: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/rAiYTsqJJR0KP8UN8vCnJMoVkda.jpg',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    audioFormats: ['Dolby Atmos', 'DTS-HD MA 5.1'],
    subtitleLanguages: ['English [CC]', 'German'],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    hasDolbyIntro: true,
  },
  {
    id: 'cyberpunk-edgerunners',
    title: 'Cyberpunk: Edgerunners',
    tagline: 'Stay human or lose your mind.',
    overview: 'A street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner: a mercenary outlaw also known as a cyberpunk.',
    type: 'series',
    runtime: '1 Season • 10 Episodes',
    releaseYear: 2022,
    rating: 'TV-MA',
    matchScore: 95,
    genres: ['Animation', 'Action', 'Sci-Fi', 'Cyberpunk'],
    badges: ['4K UHD', 'Dolby Atmos', 'HDR10+'],
    posterUrl: 'https://image.tmdb.org/t/p/w780/7jswOc6jWwB6GV5B3tH1l0fR4T3.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    director: 'Hiroyuki Imaishi',
    cast: ['KENN', 'Aoi Yuuki', 'Hiroki Touchi', 'Michiko Kaiden'],
    audioFormats: ['Japanese Atmos 5.1', 'English Atmos 5.1'],
    subtitleLanguages: ['English [CC]', 'Japanese'],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    hasDolbyIntro: false,
    seasonsCount: 1,
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodeCount: 10,
        episodes: [
          {
            id: 'edgerunners-s01e01',
            seasonNumber: 1,
            episodeNumber: 1,
            title: 'Let You Down',
            overview: 'David Martinez strives to fulfill his mother’s wish for him to reach the top of Arasaka.',
            runtime: '24m',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
            progressMinutes: 24,
            totalMinutes: 24,
            skipMarkers: { introStart: 90, introEnd: 180, outroStart: 1350 },
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
          },
          {
            id: 'edgerunners-s01e02',
            seasonNumber: 1,
            episodeNumber: 2,
            title: 'Like a Boy',
            overview: 'With military chrome implanted in his spine, David encounters a netrunner named Lucy on the night train.',
            runtime: '25m',
            thumbnailUrl: 'https://image.tmdb.org/t/p/w500/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
            progressMinutes: 12,
            totalMinutes: 25,
            skipMarkers: { introStart: 85, introEnd: 175, outroStart: 1400 },
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    tagline: 'The key to the future is finally unearthed.',
    overview: 'Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what’s left of society into chaos.',
    type: 'movie',
    runtime: '2h 44m',
    releaseYear: 2017,
    rating: 'R',
    matchScore: 94,
    genres: ['Science Fiction', 'Mystery', 'Drama'],
    badges: ['4K UHD', 'Dolby Atmos', 'Dolby Vision'],
    posterUrl: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg',
    director: 'Denis Villeneuve',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    audioFormats: ['English (Dolby Atmos 7.1)'],
    subtitleLanguages: ['English [CC]'],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    hasDolbyIntro: true,
  }
];

export const MOCK_CONTINUE_WATCHING: ContinueWatchingItem[] = [];

export const MOCK_SEGMENTS: MediaSegment[] = [
  {
    id: 'seg-1',
    type: 'INTRO',
    title: 'Opening Sequence & Theme',
    buttonLabel: 'Skip Intro',
    startSeconds: 85,
    endSeconds: 175,
    source: 'mock',
  },
  {
    id: 'seg-2',
    type: 'RECAP',
    title: 'Previously on Edgerunners',
    buttonLabel: 'Skip Recap',
    startSeconds: 0,
    endSeconds: 45,
    source: 'mock',
  },
  {
    id: 'seg-3',
    type: 'OUTRO',
    title: 'Closing Credits',
    buttonLabel: 'Next Episode',
    startSeconds: 1350,
    endSeconds: 1470,
    source: 'mock',
  }
];

export const MOCK_WATCH_GROUP: WatchGroup = {
  id: 'cinema-suite-alpha',
  name: 'Dinu & Kanmani VIP Cinema Suite',
  state: 'WAITING',
  hostId: 'dinu',
  controlMode: 'EVERYONE',
  participants: [
    {
      id: 'dinu',
      name: 'Dinu',
      avatarUrl: '/avatars/characters/iron-man.svg',
      isHost: true,
      isOnline: true,
      isReady: true,
      playbackPositionSeconds: 0,
      syncLatencyMs: 4,
      statusText: 'Synchronized • Master Clock',
    },
    {
      id: 'kanmani',
      name: 'Kanmani',
      avatarUrl: '/avatars/characters/spider-man.svg',
      isHost: false,
      isOnline: true,
      isReady: true,
      playbackPositionSeconds: 0,
      syncLatencyMs: 12,
      statusText: 'Synchronized • Cinema Display',
    },
  ],
  selectedMovie: null,
  queue: [],
  syncProgress: {
    state: 'ready',
    percent: 100,
    speed: '—',
    eta: '0s',
    currentStep: 'Ready',
  },
  currentPositionSeconds: 0,
  isPlaying: false,
  createdAt: new Date().toISOString(),
  jellyfinSyncPlayGroupId: 'syncplay-group-777',
};

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    groupId: 'cinema-suite-alpha',
    senderId: 'dinu',
    senderName: 'Dinu',
    senderAvatar: '/avatars/characters/iron-man.svg',
    text: 'Audio profile is locked into TrueHD 7.1 Atmos. The bass response is incredible!',
    timestamp: Date.now() - 180000,
    reactions: {
      '🔥': { emoji: '🔥', users: ['kanmani'], count: 1 },
      '❤️': { emoji: '❤️', users: ['kanmani'], count: 1 },
    },
  },
  {
    id: 'msg-2',
    groupId: 'cinema-suite-alpha',
    senderId: 'kanmani',
    senderName: 'Kanmani',
    senderAvatar: '/avatars/characters/spider-man.svg',
    text: 'The colors on the Sandworm sequence look breathtaking on this screen. Ready for the climax!',
    timestamp: Date.now() - 90000,
    reactions: {
      '👏': { emoji: '👏', users: ['dinu'], count: 1 },
    },
  }
];

export const MOCK_ADMIN_TELEMETRY: AdminTelemetrySummary = {
  jellyfin: {
    name: 'Jellyfin Media Server',
    status: 'healthy',
    latencyMs: 12,
    uptime: '99.98%',
    details: 'Direct Stream active • Hardware NVENC Transcode Ready',
    endpoint: 'https://jellyfin.local:8096',
    lastChecked: 'Just now',
  },
  syncManager: {
    name: 'Sync Engine & Cache Daemon',
    status: 'healthy',
    latencyMs: 3,
    uptime: '100%',
    details: 'Zero buffer starvation • 3 cached preloads verified',
    lastChecked: 'Just now',
  },
  googleDrive: {
    name: 'High-Speed Cloud Vault',
    status: 'healthy',
    latencyMs: 24,
    uptime: '99.9%',
    details: 'API Quota: 12% used • Multi-thread Rclone ready',
    lastChecked: '1m ago',
  },
  firebase: {
    name: 'Realtime Sync & Presence',
    status: 'healthy',
    latencyMs: 8,
    uptime: '100%',
    details: 'WebSocket ping 8ms • Latency compensation active',
    lastChecked: 'Just now',
  },
  storage: {
    totalGb: 200,
    usedGb: 0,
    freeGb: 200,
    usedPercentage: 0,
    breakdown: {
      moviesGb: 0,
      seriesGb: 0,
      spatialAudioGb: 0,
      systemBufferGb: 0,
    },
  },
  cachedMedia: [],
  syncJobs: [],
  livePlayback: null,
};
