import { MediaItem, ContinueWatchingItem } from '@/types/cinema';

export const FEATURED_HERO_MEDIA: MediaItem = {
  id: 'dune-part-two',
  title: 'Dune: Part Two',
  tagline: 'Long live the fighters.',
  overview:
    'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.',
  type: 'movie',
  backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=2000&auto=format&fit=crop',
  posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
  releaseYear: 2024,
  rating: 'PG-13',
  runtime: '2h 46m',
  matchScore: 99,
  genres: ['Sci-Fi', 'Adventure', 'Action', 'Drama'],
  badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD', 'IMAX Enhanced'],
  director: 'Denis Villeneuve',
  cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Austin Butler', 'Josh Brolin'],
  audioFormats: ['Dolby Atmos TrueHD 7.1', 'Dolby Digital Plus 5.1', 'PCM 2.0 Stereo'],
  subtitleLanguages: ['English [CC]', 'English SDH', 'Tamil', 'Spanish', 'French', 'Japanese'],
  trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
  hasDolbyIntro: true,
};

export const MOCK_CONTINUE_WATCHING: ContinueWatchingItem[] = [
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2023,
    rating: 'R',
    runtime: '3h 00m',
    matchScore: 98,
    genres: ['Biography', 'Drama', 'History'],
    badges: ['Dolby Atmos', '4K UHD', 'IMAX Enhanced'],
    progressMinutes: 114,
    totalMinutes: 180,
    lastWatched: 'Yesterday with Kanmani',
  },
  {
    id: 'severance-s1',
    title: 'Severance',
    overview: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2022,
    rating: 'TV-MA',
    runtime: '1 Season',
    matchScore: 97,
    genres: ['Drama', 'Sci-Fi', 'Mystery'],
    badges: ['4K UHD', 'Dolby Vision'],
    progressMinutes: 42,
    totalMinutes: 54,
    currentSeasonNumber: 1,
    currentEpisodeNumber: 8,
    currentEpisodeTitle: 'What\'s for Dinner?',
    lastWatched: '2 days ago',
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    overview: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot is tasked to pilot a spacecraft along with a team of researchers.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2014,
    rating: 'PG-13',
    runtime: '2h 49m',
    matchScore: 99,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    badges: ['Dolby Atmos', 'IMAX Enhanced', '4K UHD'],
    progressMinutes: 98,
    totalMinutes: 169,
    lastWatched: 'Last week with Dinu',
  },
  {
    id: 'the-last-of-us',
    title: 'The Last of Us',
    overview: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2023,
    rating: 'TV-MA',
    runtime: '1 Season',
    matchScore: 98,
    genres: ['Action', 'Adventure', 'Drama'],
    badges: ['4K UHD', 'Dolby Atmos', 'Dolby Vision'],
    progressMinutes: 28,
    totalMinutes: 75,
    currentSeasonNumber: 1,
    currentEpisodeNumber: 3,
    currentEpisodeTitle: 'Long, Long Time',
    lastWatched: '3 days ago',
  },
  {
    id: 'succession',
    title: 'Succession',
    overview: 'The Roy family is known for controlling the biggest media and entertainment company in the world.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2023,
    rating: 'TV-MA',
    runtime: '4 Seasons',
    matchScore: 99,
    genres: ['Drama'],
    badges: ['4K UHD', 'Dolby Vision'],
    progressMinutes: 51,
    totalMinutes: 62,
    currentSeasonNumber: 4,
    currentEpisodeNumber: 3,
    currentEpisodeTitle: 'Connor\'s Wedding',
    lastWatched: '5 days ago with Kanmani',
  },
];

export const MOCK_TRENDING: MediaItem[] = [
  {
    id: 'shogun',
    title: 'Shōgun',
    tagline: 'When destiny calls, silence answers.',
    overview: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Toranaga discovers secrets that could tip the scales of power in feudal Japan.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '1 Season',
    matchScore: 99,
    genres: ['Drama', 'History', 'Adventure'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'civil-war',
    title: 'Civil War',
    tagline: 'Welcome to the frontline.',
    overview: 'A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'R',
    runtime: '1h 49m',
    matchScore: 95,
    genres: ['Action', 'Thriller', 'Drama'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'fallout',
    title: 'Fallout',
    tagline: 'The end was only the beginning.',
    overview: 'In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation and mutants.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '1 Season',
    matchScore: 97,
    genres: ['Sci-Fi', 'Action', 'Adventure'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'the-bear',
    title: 'The Bear',
    tagline: 'Every second counts.',
    overview: 'A young chef from the fine dining world comes home to Chicago to run his family Italian beef sandwich shop.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '3 Seasons',
    matchScore: 98,
    genres: ['Comedy', 'Drama'],
    badges: ['4K UHD', 'Dolby Vision'],
  },
  {
    id: 'challengers',
    title: 'Challengers',
    tagline: 'Her game. Her rules.',
    overview: 'Tashi, a tennis player-turned-coach, has taken her husband Art and transformed him from a mediocre player into a world-famous grand slam champion.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'R',
    runtime: '2h 11m',
    matchScore: 94,
    genres: ['Drama', 'Romance', 'Sport'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'across-the-spider-verse',
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'It\'s how you wear the mask that matters.',
    overview: 'Miles Morales catapults across the Multiverse, encountering a team of Spider-People charged with protecting its very existence.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2023,
    rating: 'PG',
    runtime: '2h 20m',
    matchScore: 99,
    genres: ['Animation', 'Action', 'Adventure'],
    badges: ['Dolby Atmos', '4K UHD', 'IMAX Enhanced'],
  },
];

export const MOCK_RECENTLY_ADDED: MediaItem[] = [
  {
    id: 'furiosa',
    title: 'Furiosa: A Mad Max Saga',
    tagline: 'Out of nowhere, she rose.',
    overview: 'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'R',
    runtime: '2h 28m',
    matchScore: 96,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'alien-romulus',
    title: 'Alien: Romulus',
    tagline: 'In space no one can hear you scream.',
    overview: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'R',
    runtime: '1h 59m',
    matchScore: 95,
    genres: ['Horror', 'Sci-Fi'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD', 'IMAX Enhanced'],
  },
  {
    id: 'twisters',
    title: 'Twisters',
    tagline: 'Chase the storm.',
    overview: 'An update to the 1996 film \'Twister\', which centered on a pair of storm chasers who risk their lives in an attempt to test an experimental weather alert system.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'PG-13',
    runtime: '2h 02m',
    matchScore: 93,
    genres: ['Action', 'Adventure', 'Thriller'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'presumed-innocent',
    title: 'Presumed Innocent',
    tagline: 'Guilt is a matter of perspective.',
    overview: 'A horrific murder upends the Chicago Prosecuting Attorney\'s office when one of its own is suspected of the crime.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '1 Season',
    matchScore: 96,
    genres: ['Crime', 'Drama', 'Mystery'],
    badges: ['4K UHD', 'Dolby Vision'],
  },
  {
    id: 'planet-of-apes',
    title: 'Kingdom of the Planet of the Apes',
    tagline: 'No one can stop the reign.',
    overview: 'Many years after the reign of Caesar, a young ape goes on a journey that will lead him to question everything he\'s been taught about the past.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'PG-13',
    runtime: '2h 25m',
    matchScore: 94,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
];

export const MOCK_MOVIES: MediaItem[] = [
  {
    id: 'dc',
    title: 'DC',
    tagline: 'Justice redefined.',
    overview: 'A high-octane cinematic journey following an undercover operative confronting syndicate powers.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'PG-13',
    runtime: '2h 15m',
    matchScore: 98,
    genres: ['Action', 'Thriller', 'Crime'],
    badges: ['Dolby Atmos', '4K UHD', 'Dolby Vision'],
  },
  {
    id: 'kudumbasthan',
    title: 'Kudumbasthan',
    tagline: 'Heart of the family.',
    overview: 'An emotionally captivating drama chronicling the bonds, challenges, and resilience of a close-knit household.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'U/A',
    runtime: '2h 22m',
    matchScore: 97,
    genres: ['Drama', 'Family'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'good-night',
    title: 'Good Night',
    tagline: 'A comedy of slumber.',
    overview: 'A charming, heartfelt tale about life, love, snoring, and the endearing quirks that bring two souls together.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2023,
    rating: 'U/A',
    runtime: '2h 18m',
    matchScore: 99,
    genres: ['Romance', 'Comedy', 'Drama'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'vishwanath-and-sons',
    title: 'Vishwanath and Sons',
    tagline: 'Generations of trust and ambition.',
    overview: 'A sweeping family drama centered around a legacy jeweler navigating modernization, rivalries, and brotherhood.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'U/A',
    runtime: '2h 30m',
    matchScore: 96,
    genres: ['Drama', 'Crime', 'Family'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'blade-runner-2049',
    title: 'Blade Runner 2049',
    tagline: 'There is still a page left.',
    overview: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2017,
    rating: 'R',
    runtime: '2h 44m',
    matchScore: 98,
    genres: ['Sci-Fi', 'Mystery', 'Action'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'inception',
    title: 'Inception',
    tagline: 'Your mind is the scene of the crime.',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2010,
    rating: 'PG-13',
    runtime: '2h 28m',
    matchScore: 99,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    badges: ['4K UHD', 'Dolby Atmos'],
  },
  {
    id: 'the-batman',
    title: 'The Batman',
    tagline: 'Unmask the truth.',
    overview: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2022,
    rating: 'PG-13',
    runtime: '2h 56m',
    matchScore: 95,
    genres: ['Action', 'Crime', 'Drama'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'top-gun-maverick',
    title: 'Top Gun: Maverick',
    tagline: 'Feel the need.',
    overview: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a specialized mission.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2022,
    rating: 'PG-13',
    runtime: '2h 10m',
    matchScore: 99,
    genres: ['Action', 'Drama'],
    badges: ['Dolby Atmos', 'Dolby Vision', 'IMAX Enhanced'],
  },
  {
    id: 'arrival',
    title: 'Arrival',
    tagline: 'Why are they here?',
    overview: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2016,
    rating: 'PG-13',
    runtime: '1h 56m',
    matchScore: 97,
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
];

export const MOCK_SERIES: MediaItem[] = [
  {
    id: 'house-of-the-dragon',
    title: 'House of the Dragon',
    tagline: 'Fire will reign.',
    overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires fall from without; for them, the downfall began from within.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '2 Seasons',
    matchScore: 97,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'arcane',
    title: 'Arcane: League of Legends',
    tagline: 'Every hero has a beginning.',
    overview: 'Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-14',
    runtime: '2 Seasons',
    matchScore: 99,
    genres: ['Animation', 'Action', 'Sci-Fi'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
  {
    id: 'dark',
    title: 'Dark',
    tagline: 'The question is not where, but when.',
    overview: 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2020,
    rating: 'TV-MA',
    runtime: '3 Seasons',
    matchScore: 99,
    genres: ['Crime', 'Drama', 'Mystery', 'Sci-Fi'],
    badges: ['4K UHD', 'Dolby Vision'],
  },
  {
    id: 'true-detective',
    title: 'True Detective',
    tagline: 'Touch darkness and darkness touches you back.',
    overview: 'Seasonal anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.',
    type: 'series',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'TV-MA',
    runtime: '4 Seasons',
    matchScore: 96,
    genres: ['Crime', 'Drama', 'Mystery'],
    badges: ['4K UHD', 'Dolby Vision'],
  },
];

export const MOCK_DOLBY_ATMOS: MediaItem[] = [
  {
    id: 'dune-part-two',
    title: 'Dune: Part Two',
    overview: 'Uncompressed Dolby Atmos true spatial mix with deep infrasonic bass calibrated for reference subwoofers.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2024,
    rating: 'PG-13',
    runtime: '2h 46m',
    matchScore: 99,
    genres: ['Sci-Fi', 'Action'],
    badges: ['Dolby Atmos', 'IMAX Enhanced'],
  },
  {
    id: 'top-gun-maverick',
    title: 'Top Gun: Maverick',
    overview: 'Reference sonic experience featuring directional cockpit audio, jet engine roar, and spatial surround envelopment.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2022,
    rating: 'PG-13',
    runtime: '2h 10m',
    matchScore: 99,
    genres: ['Action'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'ford-v-ferrari',
    title: 'Ford v Ferrari',
    overview: 'Oscar-winning sound design with mechanical engine reverberation and positional trackside sound panning.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    releaseYear: 2019,
    rating: 'PG-13',
    runtime: '2h 32m',
    matchScore: 98,
    genres: ['Action', 'Biography', 'Drama'],
    badges: ['Dolby Atmos', '4K UHD'],
  },
  {
    id: 'the-matrix',
    title: 'The Matrix',
    overview: 'The 4K Dolby Atmos remaster featuring bullet-time sound trajectories and digital synthesizer spatial dynamics.',
    type: 'movie',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop',
    posterUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    releaseYear: 1999,
    rating: 'R',
    runtime: '2h 16m',
    matchScore: 99,
    genres: ['Action', 'Sci-Fi'],
    badges: ['Dolby Atmos', 'Dolby Vision', '4K UHD'],
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Sync Room Ready',
    message: 'Kanmani is online and waiting in the private screening room.',
    time: '5m ago',
    type: 'sync',
    unread: true,
  },
  {
    id: 'notif-2',
    title: '4K Dolby Atmos Master Added',
    message: '"Dune: Part Two" has been cached to local NVMe SSD storage.',
    time: '2h ago',
    type: 'media',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'Continue Watching',
    message: 'You have 42 minutes left in "Severance" Season 1.',
    time: 'Yesterday',
    type: 'resume',
    unread: false,
  },
];

export function enrichMediaItem(item: MediaItem): MediaItem {
  return {
    ...item,
    director: item.director || 'Christopher Nolan',
    cast: item.cast || ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    audioFormats: item.audioFormats || [
      'Dolby Atmos TrueHD 7.1',
      'Dolby Digital Plus 5.1',
      'PCM 2.0 Stereo',
    ],
    subtitleLanguages: item.subtitleLanguages || [
      'English [CC]',
      'English SDH',
      'Tamil',
      'Spanish',
      'French',
    ],
    trailerUrl: item.trailerUrl || 'https://www.youtube.com',
  };
}

export const ALL_MEDIA: MediaItem[] = [
  FEATURED_HERO_MEDIA,
  ...MOCK_CONTINUE_WATCHING,
  ...MOCK_TRENDING,
  ...MOCK_RECENTLY_ADDED,
  ...MOCK_MOVIES,
  ...MOCK_SERIES,
  ...MOCK_DOLBY_ATMOS,
].map(enrichMediaItem);

export function getMediaById(id: string): MediaItem | undefined {
  const found = ALL_MEDIA.find((m) => m.id === id);
  if (found) return found;
  return ALL_MEDIA.find((m) => m.id.toLowerCase() === id.toLowerCase());
}

export function getSimilarMedia(currentId: string, limit = 6): MediaItem[] {
  const current = getMediaById(currentId);
  const others = ALL_MEDIA.filter((m) => m.id !== currentId);
  if (!current) return others.slice(0, limit);
  const matching = others.filter((m) =>
    m.genres.some((g) => current.genres.includes(g))
  );
  const unique = Array.from(new Set([...matching, ...others]));
  return unique.slice(0, limit);
}

